stages:
- name: Docker Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: api:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.thedeathstarco.com
    when:
      event: {}
timeout: 60
notification: {}
