stages:
- name: Docker Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: api:dev-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: registry.thedeathstarco.com
    when:
      event: {}
- name: Deploy API Stage
  steps:
  - applyYamlConfig:
      path: ./.k8s/deployment-api.yml
- name: Deploy Worker Stage
  steps:
  - applyYamlConfig:
      path: ./.k8s/deployment-worker.yml
timeout: 60
branch:
  include:
  - develop
  - auto_deploy
notification: {}
