stages:
- name: Docker Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: api:dev-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: registry.thedeathstarco.com
    when:
      event: {}
- name: Deploy Stage
  steps:
  - applyYamlConfig:
      path: ./.k8s/deployment.yml
timeout: 60
branch:
  include:
  - develop
notification:
  recipients:
  - recipient: "#elite-document-project"
    notifier: "c-wdgl9:n-4pqbf"
  # Select which statuses you want the notification to be sent  
  condition: ["Failed", "Success"]
