version: '3'
services:

  #Python Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: crmapi:dev
    container_name: crmapi
    restart: unless-stopped
    tty: true
    ports:
      - "5000:5000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
#      DB_DATABASE: crmdb
#      DB_USERNAME: crmdev
#      DB_PASSWORD: secret
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/.env.local:/app/.env
    networks:
      - app-network

#  #Nginx Service
#  webserver:
#    image: nginx:alpine
#    container_name: webserver
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./:/var/www/html
#      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
#    networks:
#      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: crmdb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
#      MYSQL_DATABASE: crmdb
#      MYSQL_USER: crmdev
#      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/_data:/var/lib/mysql
      - ./sql/:/tmp/sql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
