version: '3'

services:
  # Python Service
  app:
    depends_on:
      - worker
      - scheduler
      - redis
      - dbsvc
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: registry.thedeathstarco.com/api:dev
    container_name: api
    restart: unless-stopped
    tty: true
    ports:
      - '5000:5000'
    environment:
      BOILERPLATE_ENV: dev
      POSTGRES_SERVICE: dbsvc
      POSTGRES_DB: dstar
      POSTGRES_USER: dstaruser
      POSTGRES_PASSWORD: password123
      REDIS_URL: redis://redis
    env_file:
      - ./docker/api.env
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/api.env:/app/.env
    networks:
      - app-network

  # Background Worker
  worker:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: registry.thedeathstarco.com/api:dev
    container_name: worker
    restart: unless-stopped
    tty: true
    environment:
      BOILERPLATE_ENV: dev
      POSTGRES_SERVICE: dbsvc
      POSTGRES_DB: dstar
      POSTGRES_USER: dstaruser
      POSTGRES_PASSWORD: password123
      REDIS_URL: redis://redis
      SCRAPYJS_URL: http://scrapyjs:8050
    working_dir: /app
    command: ['python', 'manage.py', 'worker', 'default']
    volumes:
      - ./:/app
      - ./docker/api.env:/app/.env
    networks:
      - app-network

  # Background Schedule Worker
  scheduler:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: registry.thedeathstarco.com/api:dev
    container_name: scheduler
    restart: unless-stopped
    tty: true
    environment:
      REDIS_URL: redis://redis
    working_dir: /app
    command: ['python', 'manage.py', 'kron']
    volumes:
      - ./:/app
      - ./docker/api.env:/app/.env
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

  # Browser Javascript Engine
  scrapyjs:
    image: scrapinghub/splash
    container_name: scrapyjs
    expose:
      - 8050
    networks:
      - app-network

# Postgres Service
  dbsvc:
    image: postgres:11
    volumes:
      - ./docker/_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dstar
      POSTGRES_USER: dstaruser
      POSTGRES_PASSWORD: password123
    restart: always
    ports:
      - '5432:5432'
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
