# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-19.10"
  config.vm.box_version = "201910.31.0"

  # TODO: https://askubuntu.com/a/854396

  # Provision
  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.boot_timeout = 1200
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.synced_folder "../", "/home/vagrant/", create: true
  # config.vm.provider "virtualbox" do |v|
  #   v.memory = 2048
  # end
  
  config.ssh.insert_key = false
  config.ssh.forward_agent = true
end