"""empty message

Revision ID: 008ecbfd936e
Revises: 924b0251bdaf
Create Date: 2020-08-12 13:47:36.975774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '008ecbfd936e'
down_revision = '924b0251bdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('appointments', sa.Column('loc_time_zone', sa.String(length=3), nullable=True))
    op.add_column('appointments', sa.Column('phone_number', sa.String(length=255), nullable=False))
    op.alter_column('appointments', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=100))
    op.drop_column('appointments', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'phone_number')
    op.drop_column('appointments', 'loc_time_zone')
    op.drop_column('appointments', 'email')
    op.alter_column('appointments', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=100))
    # ### end Alembic commands ###
