"""empty message

Revision ID: 06d177b28644
Revises: 5e6b1d89b5d7
Create Date: 2020-10-14 09:04:20.156128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06d177b28644'
down_revision = '5e6b1d89b5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_report_data', sa.Column('request_approved', sa.Boolean(), nullable=True))
    op.add_column('credit_report_data', sa.Column('requested_balance_original', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_report_data', 'requested_balance_original')
    op.drop_column('credit_report_data', 'request_approved')
    # ### end Alembic commands ###
