"""client program state

Revision ID: 0fe357e9a2ce
Revises: 5185ece3d372
Create Date: 2020-09-14 12:11:34.703345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe357e9a2ce'
down_revision = '5185ece3d372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('program_status', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'program_status')
    # ### end Alembic commands ###
