"""Portal Callsheet Date

Revision ID: 156de2daa26a
Revises: d0ef08231b2f
Create Date: 2020-05-19 18:20:58.091363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '156de2daa26a'
down_revision = 'd0ef08231b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_callsheet', sa.Column('callsheet_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_callsheet', 'callsheet_date')
    # ### end Alembic commands ###
