"""empty message

Revision ID: 17e95c6abc91
Revises: 8cae941a79fc
Create Date: 2020-07-26 22:58:40.732840

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '17e95c6abc91'
down_revision = '8cae941a79fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_call_events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('public_id', sa.String(length=100), nullable=True),
                    sa.Column('inserted_on', sa.DateTime(), nullable=False),
                    sa.Column('updated_on', sa.DateTime(), nullable=False),
                    sa.Column('pbx_id', sa.String(), nullable=False),
                    sa.Column('pbx_call_id', sa.String(), nullable=False),
                    sa.Column('caller_number', sa.BigInteger(), nullable=False),
                    sa.Column('dialed_number', sa.BigInteger(), nullable=False),
                    sa.Column('status', sa.Enum('INITIATED', 'GOING_TO_VOICEMAIL', 'MISSED', 'MISSED_VOICEMAIL', name='calleventtype'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('pbx_call_id'),
                    sa.UniqueConstraint('public_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_call_events')
    # ### end Alembic commands ###
