"""Credit Acc Log

Revision ID: 1d08a02a1fb5
Revises: 68d42b11eae0
Create Date: 2020-06-27 21:25:01.202359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d08a02a1fb5'
down_revision = '68d42b11eae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_report_account_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('accesed_by_username', sa.String(length=50), nullable=True),
    sa.Column('was_allowed', sa.Boolean(), nullable=False),
    sa.Column('credit_report_account_id', sa.Integer(), nullable=False),
    sa.Column('inserted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
   
    op.add_column('clients', sa.Column('friendly_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'friendly_id')
    op.drop_table('credit_report_account_access')
    # ### end Alembic commands ###
