"""Lead Distro, Team, Debt Dispute, Sales Flow

Revision ID: 257ec1874a37
Revises: 17e95c6abc91
Create Date: 2020-07-30 22:04:29.400155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257ec1874a37'
down_revision = '17e95c6abc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eft_return_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name='eft_return_fee_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('last_assigned_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tot_leads', sa.Integer(), nullable=True),
    sa.Column('tot_deals', sa.Integer(), nullable=True),
    sa.Column('time_per_lead', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name='sales_board_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='teams_creator_id_fkey'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='teams_manager_id_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lead_distribution_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hunt_type', sa.String(length=40), nullable=True),
    sa.Column('flow_interval', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('last_added_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_added_id'], ['sales_board.id'], name='lead_distribution_profile_last_added_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('assigned_on', sa.DateTime(), nullable=False),
    sa.Column('closed_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('num_out_calls', sa.Integer(), nullable=True),
    sa.Column('call_duration', sa.Integer(), nullable=True),
    sa.Column('is_recycled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name='sales_flow_agent_id_fkey'),
    sa.ForeignKeyConstraint(['lead_id'], ['clients.id'], name='sales_flow_client_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name='team_members_member_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='team_members_team_id_fkey'),
    sa.PrimaryKeyConstraint('team_id', 'member_id')
    )
    op.create_table('debt_disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('p1_date', sa.DateTime(), nullable=True),
    sa.Column('p2_date', sa.DateTime(), nullable=True),
    sa.Column('noir_date', sa.DateTime(), nullable=True),
    sa.Column('sp_date', sa.DateTime(), nullable=True),
    sa.Column('fully_disputed_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='debt_disputes_client_id_fkey'),
    sa.ForeignKeyConstraint(['debt_id'], ['credit_report_data.id'], name='debt_disputes_debt_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('credit_report_data', sa.Column('enrolled_date', sa.DateTime(), nullable=True))
    op.add_column('mailbox', sa.Column('debt_collector_id', sa.Integer(), nullable=True))
    op.create_foreign_key('mailbox_debt_collector_id_fkey', 'mailbox', 'debt_collectors', ['debt_collector_id'], ['id'])
    op.add_column('users', sa.Column('modified_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'start_date')
    op.drop_column('users', 'modified_date')
    op.drop_constraint('mailbox_debt_collector_id_fkey', 'mailbox', type_='foreignkey')
    op.drop_column('mailbox', 'debt_collector_id')
    op.drop_column('credit_report_data', 'enrolled_date')
    op.drop_table('debt_disputes')
    op.drop_table('team_members')
    op.drop_table('sales_flow')
    op.drop_table('lead_distribution_profile')
    op.drop_table('teams')
    op.drop_table('sales_board')
    op.drop_table('eft_return_fee')
    # ### end Alembic commands ###
