"""empty message

Revision ID: 26d8cd1b2c97
Revises: 5d6c0886dc34
Create Date: 2020-01-27 07:51:25.349419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d8cd1b2c97'
down_revision = '5d6c0886dc34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_dispositions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inserted_on', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('public_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('select_type', sa.Enum('MANUAL', 'AUTO', name='dispositiontype'), nullable=False))
        batch_op.create_unique_constraint('client_uq_disposition_public_id', ['public_id'])
        batch_op.create_unique_constraint('client_uq_disposition_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_dispositions', schema=None) as batch_op:
        batch_op.drop_constraint('client_uq_disposition_public_id', type_='unique')
        batch_op.drop_constraint('client_uq_disposition_name', type_='unique')
        batch_op.drop_column('select_type')
        batch_op.drop_column('public_id')
        batch_op.drop_column('name')
        batch_op.drop_column('inserted_on')

    # ### end Alembic commands ###
