"""empty message

Revision ID: 2bb35af7bd49
Revises: 89cb3e766567
Create Date: 2020-02-02 12:42:53.135778

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2bb35af7bd49'
down_revision = '89cb3e766567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('state')
        batch_op.drop_column('county')
        batch_op.drop_column('zip4')
        batch_op.drop_column('zip')
        batch_op.drop_column('city')
        batch_op.drop_column('phone')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('state')
        batch_op.drop_column('county')
        batch_op.drop_column('zip4')
        batch_op.drop_column('zip')
        batch_op.drop_column('city')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # We don't want to go back to this place of addresses on candidate/client
    pass

    # ### end Alembic commands ###
