"""empty message

Revision ID: 33474cb2d87b
Revises: 17e3574ab4cf
Create Date: 2020-01-31 02:02:51.169173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33474cb2d87b'
down_revision = '17e3574ab4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_data', schema=None) as batch_op:
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_data', schema=None) as batch_op:
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
