"""empty message

Revision ID: 36bb04429b40
Revises: 33474cb2d87b
Create Date: 2020-02-01 15:33:17.076477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bb04429b40'
down_revision = '33474cb2d87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('credit_report_data_uq_public_id', ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_data', schema=None) as batch_op:
        batch_op.drop_constraint('credit_report_data_uq_public_id', type_='unique')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
