"""Debt Collector

Revision ID: 3e295f6460be
Revises: 7a38caaaa268
Create Date: 2020-04-21 19:41:16.549266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e295f6460be'
down_revision = '7a38caaaa268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_collectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('inserted_on', sa.DateTime(), nullable=True),
    sa.Column('created_by_username', sa.String(length=50), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by_username', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('fax', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debt_collectors')
    # ### end Alembic commands ###
