"""empty message

Revision ID: 3fb40764934b
Revises: e4fb59b10a4c
Create Date: 2020-01-11 16:11:55.910328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fb40764934b'
down_revision = 'e4fb59b10a4c'
branch_labels = None
depends_on = None


def upgrade():

    session_type = postgresql.ENUM('NewContract', 'ModifyDebts', name='sessiontype')
    session_type.create(op.get_bind())

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.Enum('EMPLOYED', 'RETIRED', 'STUDENT', 'UNEMPLOYED', name='employmentstatus'), nullable=True))

    with op.batch_alter_table('docusign_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_type', sa.Enum('NewContract', 'ModifyDebts', name='sessiontype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docusign_session', schema=None) as batch_op:
        batch_op.drop_column('session_type')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('employment_status')
        batch_op.drop_column('dob')
