"""empty message

Revision ID: 4074b0bc47b3
Revises: fbfacb0ee6c0
Create Date: 2019-12-21 13:28:54.233361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4074b0bc47b3'
down_revision = 'fbfacb0ee6c0'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_dispositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('credit_payment_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enrolled_percent', sa.Float(), nullable=False),
    sa.Column('monthly_bank_fee', sa.Float(), nullable=False),
    sa.Column('minimum_fee', sa.Float(), nullable=False),
    sa.Column('monitoring_fee_1signer', sa.Float(), nullable=False),
    sa.Column('monitoring_fee_2signer', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('client_contact_numbers',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contact_number_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_number_id'], ['contact_numbers.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'contact_number_id')
    )
    op.create_table('docusign_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('PROGRESS', 'COMPLETED', 'FAILED', name='sessionstate'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('cosign_required', sa.Boolean(), nullable=True),
    sa.Column('co_client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['co_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['docusign_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disposition_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ssn', sa.String(length=11), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_foreign_key('fk_disposition_id', 'client_dispositions', ['disposition_id'], ['id'])

    with op.batch_alter_table('credit_report_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('term', sa.Integer(), nullable=True))

    with op.batch_alter_table('docusign_signature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_clients_client_id', type_='foreignkey')
        batch_op.drop_constraint('fk_docusign_template_template_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_docusign_session', 'docusign_session', ['session_id'], ['id'])
        batch_op.drop_column('template_id')
        batch_op.drop_column('created_date')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docusign_signature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('created_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('template_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'docusign_template', ['template_id'], ['id'])
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.drop_column('session_id')
        batch_op.drop_column('modified')

    with op.batch_alter_table('credit_report_accounts', schema=None) as batch_op:
        batch_op.drop_column('term')
        batch_op.drop_column('payment_start_date')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('ssn')
        batch_op.drop_column('dob')
        batch_op.drop_column('disposition_id')

    op.drop_table('docusign_session')
    op.drop_table('client_contact_numbers')
    op.drop_table('credit_payment_plan')
    op.drop_table('client_dispositions')
    # ### end Alembic commands ###
