"""ba owner type

Revision ID: 5185ece3d372
Revises: aed2f9c121c9
Create Date: 2020-09-07 21:43:58.472701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5185ece3d372'
down_revision = 'aed2f9c121c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('owner_type', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'owner_type')
    # ### end Alembic commands ###
