"""Portal Claim Callsheet

Revision ID: 6201629f612a
Revises: a73997e06169
Create Date: 2020-05-18 00:59:39.932768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6201629f612a'
down_revision = 'a73997e06169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_users', sa.Column('invite_token', sa.String(length=128), nullable=True))
    op.add_column('portal_users', sa.Column('is_claimed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_users', 'is_claimed')
    op.drop_column('portal_users', 'invite_token')
    # ### end Alembic commands ###
