"""Campaign enhancements

Revision ID: 66d8422947fd
Revises: 679c3e13c34b
Create Date: 2020-06-29 20:35:46.949833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66d8422947fd'
down_revision = '679c3e13c34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('cost_per_piece', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('est_debt_range', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('mail_type', sa.String(length=40), nullable=True))
    op.add_column('campaigns', sa.Column('marketing_model', sa.String(length=40), nullable=True))
    op.add_column('campaigns', sa.Column('num_mail_pieces', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('pinnacle_phone_no', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'pinnacle_phone_no')
    op.drop_column('campaigns', 'num_mail_pieces')
    op.drop_column('campaigns', 'marketing_model')
    op.drop_column('campaigns', 'mail_type')
    op.drop_column('campaigns', 'est_debt_range')
    op.drop_column('campaigns', 'cost_per_piece')
    # ### end Alembic commands ###
