"""Candidate Docs

Revision ID: 68d42b11eae0
Revises: b54ac7c7b06e
Create Date: 2020-06-26 16:30:38.254111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68d42b11eae0'
down_revision = 'b54ac7c7b06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('inserted_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_username', sa.String(length=50), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('updated_by_username', sa.String(length=50), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=35), nullable=True),
    sa.Column('doc_name', sa.String(length=100), nullable=True),
    sa.Column('source_channel', sa.String(length=25), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('orig_file_name', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='fk_doc_candidate_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_docs')
    # ### end Alembic commands ###
