"""empty message

Revision ID: 6e734a949c0f
Revises: 9ba9cdca1f5f
Create Date: 2019-12-06 14:03:01.664554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e734a949c0f'
down_revision = '9ba9cdca1f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inserted_on', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('gross_salary_frequency', sa.Enum('ANNUAL', 'MONTHLY', name='frequencystatus'), nullable=True),
    sa.Column('other_income', sa.Float(), nullable=False),
    sa.Column('other_income_frequency', sa.Enum('ANNUAL', 'MONTHLY', name='frequencystatus'), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_employments',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'employment_id')
    )
    op.create_table('candidate_employments',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], ),
    sa.PrimaryKeyConstraint('candidate_id', 'employment_id')
    )
    with op.batch_alter_table('docusign_template', schema=None) as batch_op:
        batch_op.create_unique_constraint('ds_key', ['ds_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docusign_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('candidate_employments')
    op.drop_table('client_employments')
    op.drop_table('employments')
    # ### end Alembic commands ###
