"""empty message

Revision ID: 6efdbbb5f9d3
Revises: 73d700a1e166
Create Date: 2019-12-06 22:32:50.080547

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6efdbbb5f9d3'
down_revision = '73d700a1e166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_data', schema=None) as batch_op:
        batch_op.alter_column('graduation', type_=sa.DATETIME, nullable=True)
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_data', schema=None) as batch_op:
        batch_op.alter_column('graduation', type_=sa.VARCHAR(length=30), nullable=True)

    # purposely not bringing back the `public_id`

    # ### end Alembic commands ###
