"""rac roles

Revision ID: 719c91b70834
Revises: 588c2762fed0
Create Date: 2020-03-11 00:39:45.021832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719c91b70834'
down_revision = '588c2762fed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rac_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('inserted_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('resource', sa.String(length=30), nullable=True),
    sa.Column('sub_resource', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=125), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )

    op.create_table('rac_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('inserted_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('name_friendly', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )

    op.create_table('rac_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('inserted_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('is_deny', sa.Boolean(), nullable=True),
    sa.Column('rac_role_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rac_role_id'], ['rac_role.id'], name='fk_rac_policy_rac_role_id'),
    sa.ForeignKeyConstraint(['resource_id'], ['rac_resource.id'], name='fk_rac_policy_resource_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    
    op.add_column('users', sa.Column('rac_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_rac_role_id', 'users', 'rac_role', ['rac_role_id'], ['id'])
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_user_rac_role_id', 'users', type_='foreignkey')
    op.drop_column('users', 'rac_role_id')
    op.drop_table('rac_policy')
    op.drop_table('rac_role')
    op.drop_table('rac_resource')
    # ### end Alembic commands ###
