"""empty message

Revision ID: 74a09544ee87
Revises: a2789c0c1254
Create Date: 2020-04-06 04:15:57.281138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74a09544ee87'
down_revision = '7c77065a72a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_candidate_assignments',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('candidate_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'candidate_id')
                    )
    op.create_table('user_client_assignments',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('client_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'client_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_client_assignments')
    op.drop_table('user_candidate_assignments')
    # ### end Alembic commands ###
