"""empty message

Revision ID: 789113155a06
Revises: 1b607187235a
Create Date: 2020-08-13 14:40:00.823720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '789113155a06'
down_revision = '1b607187235a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('loc_time_zone', sa.String(length=50), nullable=False))
    op.drop_column('appointments', 'location')
    op.alter_column('appointments', 'scheduled_at',existing_type=postgresql.TIMESTAMP(timezone=False),type_=postgresql.TIMESTAMP(timezone=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'loc_time_zone')
    op.alter_column('appointments', 'scheduled_at',existing_type=postgresql.TIMESTAMP(timezone=False),type_=postgresql.TIMESTAMP(timezone=True))
    # ### end Alembic commands ###
