"""Doc Process

Revision ID: 7a38caaaa268
Revises: 74a09544ee87
Create Date: 2020-04-14 21:25:41.803813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a38caaaa268'
down_revision = '74a09544ee87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docproc_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('inserted_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('docproc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('inserted_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_username', sa.String(length=50), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('updated_by_username', sa.String(length=50), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('docproc_user_id', sa.Integer(), nullable=True),
    sa.Column('accmgr_user_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('orig_file_name', sa.String(length=1025), nullable=True),
    sa.Column('doc_name', sa.String(length=100), nullable=True),
    sa.Column('source_channel', sa.String(length=25), nullable=True),
    sa.Column('correspondence_date', sa.Date(), nullable=True),
    sa.Column('from_who', sa.String(length=75), nullable=True),
    sa.Column('debt_name', sa.String(length=100), nullable=True),
    sa.Column('creditor_name', sa.String(length=75), nullable=True),
    sa.Column('collector_name', sa.String(length=75), nullable=True),
    sa.Column('status', sa.String(length=75), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['accmgr_user_id'], ['users.id'], name='fk_docproc_accmgr_user_id'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_docproc_client_id'),
    sa.ForeignKeyConstraint(['docproc_user_id'], ['users.id'], name='fk_docproc_user_id'),
    sa.ForeignKeyConstraint(['type_id'], ['docproc_types.id'], name='fk_docproc_type_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('docproc_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('inserted_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_docproc_notes_author_user_id'),
    sa.ForeignKeyConstraint(['doc_id'], ['docproc.id'], name='fk_docproc_notes_doc_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docproc_notes')
    op.drop_table('docproc')
    op.drop_table('docproc_types')
    # ### end Alembic commands ###
