"""User Disabled

Revision ID: 7ba6577baa38
Revises: a01c59e9fff8
Create Date: 2020-08-23 00:23:51.391641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ba6577baa38'
down_revision = 'a01c59e9fff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_disabled')
    # ### end Alembic commands ###
