"""empty message

Revision ID: 7c77065a72a3
Revises: f6b3b72d4f85
Create Date: 2020-04-10 17:56:45.524515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c77065a72a3'
down_revision = 'f6b3b72d4f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_payment_contract_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('SKIP_PAYMENT', 'CHANGE_DRAFT_DATE', 'CHANGE_RECUR_DAY', 'MANUAL_ADJUSTMENT', 'REFUND', 'RE_INSTATE', 'ADD_TO_EFT', name='revisionmethod'), nullable=True),
    sa.Column('status', sa.Enum('OPENED', 'ACCEPTED', 'REJECTED', name='revisionstatus'), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name='debt_payment_revision_agent_id_fkey'),
    sa.ForeignKeyConstraint(['contract_id'], ['debt_payment_contract.id'], name='debt_payment_revision_contarct_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('team_request_types', sa.Column('code', sa.String(length=80), nullable=True))
    op.add_column('team_request_types', sa.Column('doc_sign_required', sa.Boolean(), nullable=True))
    op.add_column('team_requests', sa.Column('revision_id', sa.Integer(), nullable=True))
    op.create_foreign_key('team_requests_revision_id_fkey', 'team_requests', 'debt_payment_contract_revision', ['revision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_requests_revision_id_fkey', 'team_requests', type_='foreignkey')
    op.drop_column('team_requests', 'revision_id')
    op.drop_column('team_request_types', 'doc_sign_required')
    op.drop_column('team_request_types', 'code')
    op.drop_table('debt_payment_contract_revision')

    ## postgresql specific downgrade
    revisionstatus = postgresql.ENUM('OPENED', 'ACCEPTED', 'REJECTED', name='revisionstatus')
    revisionstatus.drop(op.get_bind())
    revisionmethod = postgresql.ENUM('SKIP_PAYMENT', 'CHANGE_DRAFT_DATE', 'CHANGE_RECUR_DAY', 'MANUAL_ADJUSTMENT', 'REFUND', 'RE_INSTATE', 'ADD_TO_EFT', name='revisionmethod')
    revisionmethod.drop(op.get_bind())
    # ### end Alembic commands ###
