"""empty message

Revision ID: 7ed01c2c41cb
Revises: d3d9d49c4a8e
Create Date: 2020-11-28 20:29:27.824854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed01c2c41cb'
down_revision = 'd3d9d49c4a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_dispute_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dispute_id'], ['debt_disputes.id'], name='debt_dispute_log_dispute_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debt_dispute_log')
    # ### end Alembic commands ###
