"""Update Client Dispos

Revision ID: 84e37f665467
Revises: 2906710ff8dc
Create Date: 2020-06-06 19:33:59.942492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84e37f665467'
down_revision = '2906710ff8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE client_dispositions SET value='DEAD: No credit card debt' WHERE value='No credit card debt'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Already BK' WHERE value='Already BK'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Cannot Afford' WHERE value='Cannot Afford'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Take off list' WHERE value='Take off list'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Working with another company' WHERE value='Working with another company'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Do not call' WHERE value='Do not call'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Paying off debt on their own' WHERE value='Paying off debt on their own'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Debt does not qualify' WHERE value='Debt does not qualify'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Not enough debt' WHERE value='Not enough debt'")
    op.execute("UPDATE client_dispositions SET value='DEAD: No contact-Not Pitched' WHERE value='No contact-Not Pitched'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Pitched DV then no contact' WHERE value='Pitched DV then no contact'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Partial Pitch then no contact' WHERE value='Partial Pitch then no contact'")
    op.execute("UPDATE client_dispositions SET value='DEAD: Heater' WHERE value='Heater'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE client_dispositions SET value='No credit card debt' WHERE value='DEAD: No credit card debt'")
    op.execute("UPDATE client_dispositions SET value='Already BK' WHERE value='DEAD: Already BK'")
    op.execute("UPDATE client_dispositions SET value='Cannot Afford' WHERE value='DEAD: Cannot Afford'")
    op.execute("UPDATE client_dispositions SET value='Take off list' WHERE value='DEAD: Take off list'")
    op.execute("UPDATE client_dispositions SET value='Working with another company' WHERE value='DEAD: Working with another company'")
    op.execute("UPDATE client_dispositions SET value='Do not call' WHERE value='DEAD: Do not call'")
    op.execute("UPDATE client_dispositions SET value='Paying off debt on their own' WHERE value='DEAD: Paying off debt on their own'")
    op.execute("UPDATE client_dispositions SET value='Debt does not qualify' WHERE value='DEAD: Debt does not qualify'")
    op.execute("UPDATE client_dispositions SET value='Not enough debt' WHERE value='DEAD: Not enough debt'")
    op.execute("UPDATE client_dispositions SET value='No contact-Not Pitched' WHERE value='DEAD: No contact-Not Pitched'")
    op.execute("UPDATE client_dispositions SET value='Pitched DV then no contact' WHERE value='DEAD: Pitched DV then no contact'")
    op.execute("UPDATE client_dispositions SET value='Partial Pitch then no contact' WHERE value='DEAD: Partial Pitch then no contact'")
    op.execute("UPDATE client_dispositions SET value='Heater' WHERE value='DEAD: Heater'")
    # ### end Alembic commands ###
