"""empty message

Revision ID: 89cb3e766567
Revises: 17e3574ab4cf
Create Date: 2020-02-01 14:18:36.422563

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '89cb3e766567'
down_revision = '17e3574ab4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    call_status = postgresql.ENUM('Planned', 'Ongoing', 'Success', 'Rejected', 'Failed', name='callstatus')
    call_status.create(op.get_bind())

    call_direction = postgresql.ENUM('Incoming', 'Outgoing', name='calldirection')
    call_direction.create(op.get_bind())

    op.create_table('client_calls',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('inserted_on', sa.DateTime(), nullable=False),
                    sa.Column('client_id', sa.Integer(), nullable=True),
                    sa.Column('agent_id', sa.Integer(), nullable=True),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=True),
                    sa.Column('duration_mins', sa.Integer(), nullable=True),
                    sa.Column('status',
                              sa.Enum('Planned', 'Ongoing', 'Success', 'Rejected', 'Failed', name='callstatus'),
                              nullable=True),
                    sa.Column('direction', sa.Enum('Incoming', 'Outgoing', name='calldirection'), nullable=False),
                    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('debt_payment_contract',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('inserted_on', sa.DateTime(), nullable=False),
                    sa.Column('sale_date', sa.DateTime(), nullable=True),
                    sa.Column('term', sa.Integer(), nullable=True),
                    sa.Column('payment_start_date', sa.DateTime(), nullable=True),
                    sa.Column('payment_recurring_begin_date', sa.DateTime(), nullable=True),
                    sa.Column('commission_rate', sa.Float(), nullable=True),
                    sa.Column('client_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_manager_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('application_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('campaign_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lead_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('modified_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('opener_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('team_manager_id_fk', 'users', ['team_manager_id'], ['id'])
        batch_op.create_foreign_key('opener_id_fk', 'users', ['opener_id'], ['id'])
        batch_op.create_foreign_key('account_manager_id_fk', 'users', ['account_manager_id'], ['id'])

    with op.batch_alter_table('credit_report_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fico', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_accounts', schema=None) as batch_op:
        batch_op.drop_column('fico')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_manager_id')
        batch_op.drop_column('opener_id')
        batch_op.drop_column('modified_date')
        batch_op.drop_column('lead_source')
        batch_op.drop_column('campaign_name')
        batch_op.drop_column('application_date')
        batch_op.drop_column('account_manager_id')

    op.drop_table('debt_payment_contract')
    op.drop_table('client_calls')

    call_status = postgresql.ENUM('Planned', 'Ongoing', 'Success', 'Rejected', 'Failed', name='callstatus')
    call_status.drop(op.get_bind())

    call_direction = postgresql.ENUM('Incoming', 'Outgoing', name='calldirection')
    call_direction.drop(op.get_bind())
    # ### end Alembic commands ###
