"""Creditor

Revision ID: 8cae941a79fc
Revises: bedaece16d8a
Create Date: 2020-07-20 20:55:24.808249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cae941a79fc'
down_revision = 'bedaece16d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inserted_on', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('fax', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('clients', sa.Column('epps_account_id', sa.String(length=100), nullable=True))
    op.add_column('debt_payment_schedule', sa.Column('desc', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debt_payment_schedule', 'desc')
    op.drop_column('clients', 'epps_account_id')
    op.drop_table('creditors')
    # ### end Alembic commands ###
