"""empty message

Revision ID: 924b0251bdaf
Revises: 26bbb568a3e4
Create Date: 2020-08-09 02:49:34.385069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '924b0251bdaf'
down_revision = '26bbb568a3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_call_events', sa.Column('receive_date', sa.DateTime(), nullable=True))

    op.execute("ALTER TABLE voice_communications ALTER COLUMN type TYPE VARCHAR(255)")
    op.execute("DROP TYPE IF EXISTS voicecommunicationtype")
    op.execute("CREATE TYPE voicecommunicationtype AS ENUM ('MISSED_CALL', 'RECORDING', 'VOICEMAIL')")
    op.execute("ALTER TABLE voice_communications ALTER COLUMN type TYPE voicecommunicationtype USING (type::voicecommunicationtype)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_call_events', 'receive_date')

    op.execute("ALTER TABLE voice_communications ALTER COLUMN type TYPE VARCHAR(255)")
    op.execute("DROP TYPE IF EXISTS voicecommunicationtype")
    op.execute("CREATE TYPE voicecommunicationtype AS ENUM ('RECORDING', 'VOICEMAIL')")
    op.execute("ALTER TABLE voice_communications ALTER COLUMN type TYPE voicecommunicationtype USING (type::voicecommunicationtype)")
    # ### end Alembic commands ###
