"""empty message

Revision ID: 9a39c01a9f0e
Revises: f93ac9a4b808
Create Date: 2020-09-22 20:23:33.936981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a39c01a9f0e'
down_revision = 'f93ac9a4b808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('requestor_id', sa.Integer(), nullable=True))
    op.create_foreign_key('audit_requestor_id_fkey', 'audit', 'users', ['requestor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audit_requestor_id_fkey', 'audit', type_='foreignkey')
    op.drop_column('audit', 'requestor_id')
    # ### end Alembic commands ###
