"""empty message

Revision ID: 9b2a035631e7
Revises: 156de2daa26a
Create Date: 2020-05-19 20:16:11.397507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b2a035631e7'
down_revision = '156de2daa26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('app_name', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.String(length=200), nullable=False),
    sa.Column('client_portal', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_name'),
    sa.UniqueConstraint('client_portal'),
    sa.UniqueConstraint('logo_url'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fname', sa.String(length=100), nullable=False),
    sa.Column('attachment', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('trigger_mode', sa.String(length=20), nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('medium', sa.String(length=20), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name='templates_uploader_id_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fname'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('mailbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('from_addr', sa.String(length=200), nullable=True),
    sa.Column('to_addr', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='mailbox_client_id_fkey'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name='mailbox_template_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointments', sa.Column('reminder_status', sa.JSON(), nullable=True))
    op.add_column('credit_report_data', sa.Column('collector_id', sa.Integer(), nullable=True))
    op.add_column('credit_report_data', sa.Column('prev_collector_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_credit_report_data_prev_collector_id', 'credit_report_data', 'debt_collectors', ['prev_collector_id'], ['id'])
    op.create_foreign_key('fk_credit_report_data_collector_id', 'credit_report_data', 'debt_collectors', ['collector_id'], ['id'])
    op.drop_column('credit_report_data', 'collector_account')
    op.drop_column('credit_report_data', 'last_collector')
    op.add_column('debt_collectors', sa.Column('account_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debt_collectors', 'account_number')
    op.add_column('credit_report_data', sa.Column('last_collector', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('credit_report_data', sa.Column('collector_account', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint('fk_credit_report_data_collector_id', 'credit_report_data', type_='foreignkey')
    op.drop_constraint('fk_credit_report_data_prev_collector_id', 'credit_report_data', type_='foreignkey')
    op.drop_column('credit_report_data', 'prev_collector_id')
    op.drop_column('credit_report_data', 'collector_id')
    op.drop_column('appointments', 'reminder_status')
    op.drop_table('mailbox')
    op.drop_table('templates')
    op.drop_table('organizations')
    # ### end Alembic commands ###
