"""empty message

Revision ID: 9ba9cdca1f5f
Revises: 47e26d604b8e
Create Date: 2019-12-03 19:24:34.839525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9ba9cdca1f5f'
down_revision = '47e26d604b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bankaccounttype = postgresql.ENUM('checking', 'savings', name='bankaccounttype')
    bankaccounttype.create(op.get_bind())

    op.add_column('bank_accounts', sa.Column('type', sa.Enum('checking', 'savings', name='bankaccounttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'type')

    bankaccounttype = postgresql.ENUM('checking', 'savings', name='bankaccounttype')
    bankaccounttype.drop(op.get_bind())
    # ### end Alembic commands ###
