"""empty message

Revision ID: 9f77ce611b32
Revises: 6e734a949c0f
Create Date: 2019-12-07 07:54:14.859791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f77ce611b32'
down_revision = '6e734a949c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docusign_signature', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['envelope_id'])

    with op.batch_alter_table('docusign_template', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ds_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docusign_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('docusign_signature', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
