"""Sales Commission

Revision ID: a01c59e9fff8
Revises: ddb123661445
Create Date: 2020-08-18 21:36:11.490285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01c59e9fff8'
down_revision = 'ddb123661445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name='sales_commissions_agent_id_fkey'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='sales_commissions_client_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['debt_payment_transaction.id'], name='sales_commissions_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_commissions')
    # ### end Alembic commands ###
