"""empty message

Revision ID: a2789c0c1254
Revises: 719c91b70834
Create Date: 2020-04-03 03:29:02.838019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2789c0c1254'
down_revision = 'dcf8bcfefc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pbx_numbers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('inserted_on', sa.DateTime(), nullable=False),
                    sa.Column('number', sa.BigInteger(), nullable=False),
                    sa.Column('department', sa.Enum('OPENERS', 'SALES', 'SERVICE', name='department'), nullable=False),
                    sa.Column('enabled', sa.Boolean(), nullable=False),
                    sa.Column('updated_on', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('number')
                    )
    op.create_table('fax_communications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('inserted_on', sa.DateTime(), nullable=False),
                    sa.Column('pbx_number_id', sa.Integer(), nullable=True),
                    sa.Column('source_number', sa.BigInteger(), nullable=False),
                    sa.Column('destination_number', sa.BigInteger(), nullable=False),
                    sa.Column('outside_number', sa.BigInteger(), nullable=True),
                    sa.Column('receive_date', sa.DateTime(), nullable=False),
                    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
                    sa.Column('provider_name', sa.String(length=25), nullable=False),
                    sa.Column('file_bucket_name', sa.String(length=50), nullable=False),
                    sa.Column('file_bucket_key', sa.String(length=1024), nullable=False),
                    sa.Column('updated_on', sa.DateTime(), nullable=False),
                    sa.Column('is_viewed', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['pbx_number_id'], ['pbx_numbers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('file_bucket_key')
                    )
    op.create_table('voice_communications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('inserted_on', sa.DateTime(), nullable=False),
                    sa.Column('pbx_number_id', sa.Integer(), nullable=True),
                    sa.Column('type', sa.Enum('RECORDING', 'VOICEMAIL', name='voicecommunicationtype'), nullable=False),
                    sa.Column('source_number', sa.BigInteger(), nullable=False),
                    sa.Column('destination_number', sa.BigInteger(), nullable=True),
                    sa.Column('outside_number', sa.BigInteger(), nullable=True),
                    sa.Column('receive_date', sa.DateTime(), nullable=False),
                    sa.Column('duration_seconds', sa.Integer(), nullable=False),
                    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
                    sa.Column('provider_name', sa.String(length=100), nullable=False),
                    sa.Column('provider_record_id', sa.String(length=100), nullable=True),
                    sa.Column('file_bucket_name', sa.String(length=50), nullable=False),
                    sa.Column('file_bucket_key', sa.String(length=1024), nullable=False),
                    sa.Column('updated_on', sa.DateTime(), nullable=False),
                    sa.Column('is_viewed', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['pbx_number_id'], ['pbx_numbers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('file_bucket_key'),
                    sa.UniqueConstraint('provider_record_id')
                    )
    op.create_table('candidate_fax_communications',
                    sa.Column('candidate_id', sa.Integer(), nullable=False),
                    sa.Column('fax_communication_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
                    sa.ForeignKeyConstraint(['fax_communication_id'], ['fax_communications.id'], ),
                    sa.PrimaryKeyConstraint('candidate_id', 'fax_communication_id')
                    )
    op.create_table('candidate_voice_communications',
                    sa.Column('candidate_id', sa.Integer(), nullable=False),
                    sa.Column('voice_communication_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
                    sa.ForeignKeyConstraint(['voice_communication_id'], ['voice_communications.id'], ),
                    sa.PrimaryKeyConstraint('candidate_id', 'voice_communication_id')
                    )
    op.create_table('user_fax_communications',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('fax_communication_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['fax_communication_id'], ['fax_communications.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'fax_communication_id')
                    )
    op.create_table('user_pbx_numbers',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('pbx_number_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['pbx_number_id'], ['pbx_numbers.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'pbx_number_id')
                    )
    op.create_table('user_voice_communications',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('voice_communication_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['voice_communication_id'], ['voice_communications.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'voice_communication_id')
                    )
    op.create_table('client_fax_communications',
                    sa.Column('client_id', sa.Integer(), nullable=False),
                    sa.Column('fax_communication_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
                    sa.ForeignKeyConstraint(['fax_communication_id'], ['fax_communications.id'], ),
                    sa.PrimaryKeyConstraint('client_id', 'fax_communication_id')
                    )
    op.create_table('client_voice_communications',
                    sa.Column('client_id', sa.Integer(), nullable=False),
                    sa.Column('voice_communication_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
                    sa.ForeignKeyConstraint(['voice_communication_id'], ['voice_communications.id'], ),
                    sa.PrimaryKeyConstraint('client_id', 'voice_communication_id')
                    )
    op.add_column('users', sa.Column('department', sa.Enum('OPENERS', 'SALES', 'SERVICE', name='department'), nullable=True))
    op.add_column('users', sa.Column('pbx_caller_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('pbx_mailbox_id', sa.String(length=25), nullable=True))
    op.create_unique_constraint('users_pbx_caller_id_key', 'users', ['pbx_mailbox_id'])
    op.create_unique_constraint('users_pbx_mailbox_id_key', 'users', ['pbx_caller_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_pbx_caller_id_key', 'users', type_='unique')
    op.drop_constraint('users_pbx_mailbox_id_key', 'users', type_='unique')
    op.drop_column('users', 'pbx_mailbox_id')
    op.drop_column('users', 'pbx_caller_id')
    op.drop_column('users', 'department')
    op.drop_table('client_voice_communications')
    op.drop_table('client_fax_communications')
    op.drop_table('user_voice_communications')
    op.drop_table('user_pbx_numbers')
    op.drop_table('user_fax_communications')
    op.drop_table('candidate_voice_communications')
    op.drop_table('candidate_fax_communications')
    op.drop_table('voice_communications')
    voice_communication_type = postgresql.ENUM('RECORDING', 'VOICEMAIL', name='voicecommunicationtype')
    voice_communication_type.drop(op.get_bind())
    op.drop_table('fax_communications')
    op.drop_table('pbx_numbers')
    department_type = postgresql.ENUM('OPENERS', 'SALES', 'SERVICE', name='department')
    department_type.drop(op.get_bind())
    # ### end Alembic commands ###
