"""candidate sms

Revision ID: b056dc242da5
Revises: 3e5b75cbc80d
Create Date: 2020-03-25 20:14:59.822968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b056dc242da5'
down_revision = '3e5b75cbc80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_convos', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_sms_convos_candidate_id', 'sms_convos', 'candidates', ['candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sms_convos_candidate_id', 'sms_convos', type_='foreignkey')
    op.drop_column('sms_convos', 'candidate_id')
    # ### end Alembic commands ###
