"""empty message

Revision ID: b54ac7c7b06e
Revises: 84e37f665467
Create Date: 2020-06-06 14:17:31.602935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b54ac7c7b06e'
down_revision = '84e37f665467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_report_accounts', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('credit_report_accounts', 'registered_fraud_insurance',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('credit_report_accounts', 'tracking_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_report_accounts', 'tracking_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('credit_report_accounts', 'registered_fraud_insurance',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('credit_report_accounts', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
