"""Client friendly ID change

Revision ID: bedaece16d8a
Revises: cf3f2b271031
Create Date: 2020-07-15 20:56:19.503979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bedaece16d8a'
down_revision = 'cf3f2b271031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'friendly_id',
                existing_type=sa.INTEGER(),
                type_=sa.VARCHAR(length=24),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE clients ALTER COLUMN friendly_id TYPE integer USING (friendly_id::integer)')
    # ### end Alembic commands ###
