"""empty message

Revision ID: c0d9a442072b
Revises: 26d8cd1b2c97
Create Date: 2020-01-27 08:16:49.246352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d9a442072b'
down_revision = '26d8cd1b2c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_dispositions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('select_type', sa.Enum('MANUAL', 'AUTO', name='dispositiontype'), nullable=False))
        batch_op.create_unique_constraint('candidate_disposition_uq_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_dispositions', schema=None) as batch_op:
        batch_op.drop_constraint('candidate_disposition_uq_name', type_='unique')
        batch_op.drop_column('select_type')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
