"""empty message

Revision ID: d3d9d49c4a8e
Revises: e17625a34cac
Create Date: 2020-10-22 18:26:05.659916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = 'd3d9d49c4a8e'
down_revision = 'e17625a34cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supermoney_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('military_status', sa.Enum('NOT_MILITARY', 'ACTIVE_RESERVE', 'VETERAN', 'DEPENDENT_OF_ACTIVE', name='militaryoptions'), nullable=True),
    sa.Column('residency_status', sa.Enum('US_CITIZEN', 'TEMP_RESIDENT_VISA', 'PERMANENT_RESIDENT', 'NON_RESIDENT', name='residencyoptions'), nullable=True),
    sa.Column('employment_status', sa.Enum('FULL_TIME', 'SELF_EMPLOYED', 'RETIRED', 'PART_TIME', 'UNEMPLOYED', 'OTHER', name='employmentoptions'), nullable=True),
    sa.Column('pay_frequency', sa.Enum('BI_WEEKLY', 'TWICE_A_MONTH', 'MONTHLY', 'WEEKLY', 'OTHER', name='payfrequencyoptions'), nullable=True),
    sa.Column('pay_method', sa.Enum('DIRECT_DEPOSIT', 'MISC_INCOME', 'PAYROLL_PREPAID', 'CASH_OTHER', name='paymethodoptions'), nullable=True),
    sa.Column('checking_account', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supermoney_options')
    if 'postgresql' in session.bind.dialect.name:
        # drop enums
        op.execute('DROP TYPE militaryoptions')
        op.execute('DROP TYPE residencyoptions')
        op.execute('DROP TYPE employmentoptions')
        op.execute('DROP TYPE payfrequencyoptions')
        op.execute('DROP TYPE paymethodoptions')
    # ### end Alembic commands ###
