"""service schedule

Revision ID: dcf8bcfefc67
Revises: b056dc242da5
Create Date: 2020-04-01 01:44:30.286206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf8bcfefc67'
down_revision = 'b056dc242da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('schedule_item', sa.Integer(), nullable=False),
    sa.Column('inserted_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by_username', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('tot_reschedule', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_svc_schedule_client_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_schedule')
    # ### end Alembic commands ###
