"""empty message

Revision ID: e17625a34cac
Revises: 06d177b28644
Create Date: 2020-10-22 08:02:39.516712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e17625a34cac'
down_revision = '06d177b28644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('best_time_pos', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'best_time_pos')
    # ### end Alembic commands ###
