"""empty message

Revision ID: e4fb59b10a4c
Revises: 6bdb19e11351
Create Date: 2020-01-06 21:41:52.460035

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e4fb59b10a4c'
down_revision = '6bdb19e11351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_payment_schedule',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('client_id', sa.Integer(), nullable=True),
                    sa.Column('due_date', sa.DateTime(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('bank_fee', sa.Float(), nullable=True),
                    sa.Column('status', sa.Enum('Scheduled', 'Processed', 'Settled', 'Failed', name='debteftstatus'), nullable=False),
                    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_client'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('debt_payment_transaction',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('trans_id', sa.String(length=40), nullable=False),
                    sa.Column('status', sa.String(length=200), nullable=False),
                    sa.Column('message', sa.Text(), nullable=True),
                    sa.Column('provider', sa.String(length=40), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=False),
                    sa.Column('payment_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['payment_id'], ['debt_payment_schedule.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))

    with op.batch_alter_table('credit_report_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_recurring_begin_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_accounts', schema=None) as batch_op:
        batch_op.drop_column('payment_recurring_begin_date')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    op.drop_table('debt_payment_transaction')
    op.drop_table('debt_payment_schedule')
    # ### end Alembic commands ###
