"""Add public_id to pbx_numbers

Revision ID: ee5919296c72
Revises: b54ac7c7b06e
Create Date: 2020-06-22 21:29:52.704220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee5919296c72'
down_revision = '1d08a02a1fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pbx_numbers', sa.Column('public_id', sa.String(length=100), nullable=True))

    op.execute("UPDATE pbx_numbers SET public_id = uuid_generate_v4() WHERE public_id is NULL")

    op.alter_column('pbx_numbers', 'public_id', nullable=False)
    op.create_unique_constraint('pbx_numbers_public_id_key', 'pbx_numbers', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pbx_numbers_public_id_key', 'pbx_numbers', type_='unique')
    op.drop_column('pbx_numbers', 'public_id')
    # ### end Alembic commands ###
