"""empty message

Revision ID: f439b7bcd64f
Revises: 2bb35af7bd49
Create Date: 2020-02-05 11:44:34.348861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f439b7bcd64f'
down_revision = '2bb35af7bd49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_dispositions', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('select_type',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)

    with op.batch_alter_table('client_dispositions', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('select_type',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)

    with op.batch_alter_table('credit_report_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint('credit_report_data_uq_disposition_public_id', ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_data', schema=None) as batch_op:
        batch_op.drop_constraint('credit_report_data_uq_disposition_public_id', type_='unique')
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('public_id')

    with op.batch_alter_table('client_dispositions', schema=None) as batch_op:
        batch_op.alter_column('select_type',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('candidate_dispositions', schema=None) as batch_op:
        batch_op.alter_column('select_type',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
