"""empty message

Revision ID: f6b3b72d4f85
Revises: 3e5b75cbc80d
Create Date: 2020-03-27 17:39:25.203172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b3b72d4f85'
down_revision = 'dcf8bcfefc67'
branch_labels = None
depends_on = None

old_options = ('NEW_CONTRACT', 'ADD_DEBTS', 'REMOVE_DEBTS', 'MODIFY_DEBTS', 'TERM_CHANGE', 'RECIEVE_SUMMON', 'ADD_COCLIENT')
new_options = sorted(old_options + ('REMOVE_COCLIENT', 'NEW_EFT_AUTH',))

old_type = sa.Enum(*old_options, name='contractaction')
new_type = sa.Enum(*new_options, name='contractaction')
tmp_type = sa.Enum(*new_options, name='_contractaction')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE debt_payment_contract ALTER COLUMN current_action TYPE _contractaction'
               ' USING current_action::text::_contractaction')
    old_type.drop(op.get_bind(), checkfirst=False)
    new_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE debt_payment_contract ALTER COLUMN current_action TYPE contractaction'
               ' USING current_action::text::contractaction')
    tmp_type.drop(op.get_bind(), checkfirst=False)

    op.add_column('debt_payment_contract', sa.Column('prev_id', sa.Integer(), nullable=True))
    op.create_foreign_key('debt_payment_contract_prev_id_fkey', 'debt_payment_contract', 'debt_payment_contract', ['prev_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('debt_payment_contract_prev_id_fkey', 'debt_payment_contract', type_='foreignkey')
    op.drop_column('debt_payment_contract', 'prev_id')
    # ### end Alembic commands ###
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE debt_payment_contract ALTER COLUMN current_action TYPE _contractaction'
               ' USING current_action::text::_contractaction')
    old_type.drop(op.get_bind(), checkfirst=False)
    new_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE debt_payment_contract ALTER COLUMN current_action TYPE contractaction'
               ' USING current_action::text::contractaction')
    tmp_type.drop(op.get_bind(), checkfirst=False)

