"""sms mssg status

Revision ID: f6f5c143345d
Revises: 719c91b70834
Create Date: 2020-03-17 00:03:59.956183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f5c143345d'
down_revision = '719c91b70834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_messages', sa.Column('delivery_status', sa.String(length=10), nullable=True))
    sms_mssg = sa.sql.table('sms_messages', sa.Column('delivery_status', sa.String))
    op.execute(sms_mssg.update().values({'delivery_status':op.inline_literal('success')}))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_messages', 'delivery_status')
    # ### end Alembic commands ###
