"""empty message

Revision ID: f93ac9a4b808
Revises: 0fe357e9a2ce
Create Date: 2020-09-20 19:29:13.118055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f93ac9a4b808'
down_revision = '0fe357e9a2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('type', sa.String(length=24), nullable=True))
    op.alter_column('appointments', 'loc_time_zone',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.drop_constraint('appointments_team_manager_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'team_manager_id')
    op.drop_column('appointments', 'reminder_status')
    op.add_column('service_schedule', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_svc_schedule_appointment_id', 'service_schedule', 'appointments', ['appointment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_svc_schedule_appointment_id', 'service_schedule', type_='foreignkey')
    op.drop_column('service_schedule', 'appointment_id')
    op.add_column('appointments', sa.Column('reminder_status', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('team_manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('appointments_team_manager_id_fkey', 'appointments', 'users', ['team_manager_id'], ['id'])
    op.alter_column('appointments', 'loc_time_zone',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.drop_column('appointments', 'type')
    # ### end Alembic commands ###
