"""empty message

Revision ID: fef91d0fe63e
Revises: 8bf322c421c2
Create Date: 2020-10-05 20:38:51.814403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fef91d0fe63e'
down_revision = '8bf322c421c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_numbers', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint('contact_numbers_phone_number_key', 'contact_numbers', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.drop_constraint('contact_numbers_phone_number_key', 'contact_numbers', type_='unique')
    op.alter_column('contact_numbers', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
