import datetime
import uuid

from pytz import utc

from app.main import db
from app.main.model.client import ClientDisposition

client_dispositions = [
    {"value": 'Inserted',"select_type": 'AUTO', "name":'Sales_ActiveStatus_InsertedLead'},
    {"value": 'New Lead',"select_type": 'AUTO', "name":'Sales_ActiveStatus_NewLead'},
    {"value": 'Renewed Lead',"select_type": 'AUTO', "name":'Sales_ActiveStatus_RenewedLead'},
    {"value": 'Partial Options Pitch',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_PartialOptionPitch'}, 
    {"value": 'Pitched Options',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_PitchedOptions' },
    {"value": 'Pitched Credit Counseling',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_PitchedCreditCounseling'}, 
    {"value": 'Pitched Debt Validation',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_PitchedDebtValidation'},
    {"value": 'Pitched Bankruptcy',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_PitchedBankruptcy'},
    {"value": 'Transferred to Credit Counseling',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_TransferredCreditCounseling' },
    {"value": 'Transferred to Bankruptcy',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_TransferredBankruptcy' },
    {"value": 'Enrolled in Credit Counseling',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_EnrolledCreditCounseling'}, 
    {"value": 'Enrolled in Bankruptcy',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_EnrolledBankruptcy'},
    {"value": 'Secured CC Payment',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_Secured_CC_Payment'},
    {"value": 'Secured BK Payment',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_Secured_BK_Payment'},
    {"value": 'Partial Paperwork In',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_PartialPaperworkIn'}, 
    {"value": 'Paperwork In',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_PaperworkIn'}, 
    {"value": 'Contract Sent',"select_type": 'AUTO', "name":'Sales_Contract_Sent'},
    {"value": 'Contract Received',"select_type": 'AUTO', "name":'Sales_Contract_Received'},
    {"value": 'Contract Opened',"select_type": 'AUTO', "name":'Sales_Contract_Opened'},
    {"value": 'Contract Viewed',"select_type": 'AUTO', "name":'Sales_Contract_Viewed'},
    {"value": 'Contract Signed',"select_type": 'AUTO', "name":'Sales_Contract_Signed'},
    {"value": 'Contract Complete',"select_type": 'AUTO', "name":'Sales_Contract_Complete'},
    {"value": 'Contract Declined',"select_type": 'AUTO', "name":'Sales_Contract_Declined'},
    {"value": 'Contract Voided',"select_type": 'AUTO', "name":'Sales_Contract_Voided'},
    {"value": 'Contract Timed out',"select_type": 'AUTO', "name":'Sales_Contract_timedout'},
    {"value": 'Acct Manager Unavailable',"select_type": 'MANUAL', "name":'Service_ActiveStatus_AcctManagerUnavailable' },
    {"value": 'Service Issue',"select_type": 'MANUAL', "name":'Service_ActiveStatus_ServiceIssue' },
    {"value": 'Sales Issue',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_SalesIssue' },
    {"value": 'Acct Manager Intro Complete',"select_type": 'AUTO', "name":'Service_ActiveStatus_AcctManagerIntroComplete' },
    {"value": 'Pending 1st Payment',"select_type": 'AUTO', "name":'Sales_ActiveStatus_PendingFirstPayment' },
    {"value": 'Active',"select_type": 'AUTO', "name":'Sales_ActiveStatus_Active' },
    {"value": 'Pending Cancellation: Client Signature',"select_type": 'MANUAL', "name":'Service_ActiveStatus_PendingClientSignatureCancellation' },
    {"value": 'Pending Cancellation: Refund',"select_type": 'MANUAL', "name":'Service_ActiveStatus_PendingRefundCancellation' },
    {"value": 'Fulfillment',"select_type": 'AUTO', "name":'Service_ActiveStatus_Fulfillment'},
    {"value": 'Graduated',"select_type": 'MANUAL', "name":'Service_ActiveStatus_Graduated'},
    {"value": 'Assign to Acct Manager',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_AssignAcctManager' },
    {"value": 'Sales:  Acct Manager Intro Incomplete',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_AcctManagerIntroIncomplete' },
    {"value": 'Sales: Deal Rejected',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_DealRejected' },
    {"value": 'Sales: Request Cancellation',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_RequestCancellation' },
    {"value": 'Sales: Deal Complete',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_DealComplete' },
    {"value": 'Service Issue:NSF',"select_type": 'AUTO', "name":'Service_ActiveStatus_NSF'},
    {"value": 'Service Issue:Draft/Banking Change',"select_type": 'MANUAL', "name":'Service_ActiveStatus_DraftBankingChange' },
    {"value": 'Service Issue:Program Change Request',"select_type": 'MANUAL', "name":'Service_ActiveStatus_ProgramChangeRequest' },
    {"value": 'Service Issue:Signature Pending',"select_type": 'AUTO', "name":'Service_ActiveStatus_SignaturePending' },
    {"value": 'Sales Issue:NSF',"select_type": 'AUTO', "name":'Sales_ActiveStatus_NSF'},
    {"value": 'Sales Issue:Draft/Banking Change',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_DraftBankingChange' },
    {"value": 'Sales Issue:Program Change Request',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_ProgramChangeRequest' },
    {"value": 'Sales Issue:Signature Pending',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_SignaturePending' },
    {"value": 'DEAD: Heater',"select_type": 'MANUAL', "name":'Sales_DeadStatus_Heater'},
    {"value": 'DEAD: No credit card debt',"select_type": 'MANUAL', "name":'Sales_DeadStatus_NoCreditCardDebt' },
    {"value": 'DEAD: Already BK',"select_type": 'MANUAL', "name":'Sales_DeadStatus_AlreadyBankrupt' },
    {"value": 'DEAD: Cannot Afford',"select_type": 'MANUAL', "name":'Sales_DeadStatus_CannotAfford' },
    {"value": 'DEAD: Take off list',"select_type": 'MANUAL', "name":'Sales_DeadStatus_TakeoffList' },
    {"value": 'DEAD: Working with another company',"select_type": 'MANUAL', "name":'Sales_DeadStatus_WorkingWithOtherCompany' },
    {"value": 'DEAD: Do not call',"select_type": 'MANUAL', "name":'Sales_DeadStatus_DoNotCall' },
    {"value": 'DEAD: Paying off debt on their own',"select_type": 'MANUAL', "name":'Sales_DeadStatus_PayingOffDebtOnTheirOwn' },
    {"value": 'DEAD: Debt does not qualify',"select_type": 'MANUAL', "name":'Sales_DeadStatus_DebtDoesNotQualify' },
    {"value": 'DEAD: Not enough debt',"select_type": 'MANUAL', "name":'Sales_DeadStatus_NotEnoughDebt' },
    {"value": 'DEAD: No contact-Not Pitched',"select_type": 'MANUAL', "name":'Sales_DeadStatus_NoContact_NotPitched' },
    {"value": 'DEAD: Pitched DV then no contact',"select_type": 'MANUAL', "name":'Sales_DeadStatus_PitchedDV_ThenNoContact' },
    {"value": 'DEAD: Partial Pitch then no contact',"select_type": 'MANUAL', "name":'Sales_DeadStatus_PartialPitch_ThenNoContact' },
    {"value": 'Cancelled before 1st:Lose Job',"select_type":'MANUAL',"name": 'Cancelled_before_1st_Lose_Job'},
    {"value": 'Cancelled before 1st:Bankruptcy',"select_type":'MANUAL',"name": 'Cancelled_before_1st_Bankruptcy'},
    {"value": 'Cancelled before 1st:Self Settlement',"select_type":'MANUAL',"name": 'Cancelled_before_1st_Self_Settlement'},
    {"value": 'Cancelled before 1st:Find another company',"select_type":'MANUAL',"name": 'Cancelled_before_1st_FindAnotherCompany'},
    {"value": 'Cancelled before 1st:Can not Afford',"select_type":'MANUAL',"name": 'Cancelled_before_1st_Can_Not_Afford'},
    {"value": 'Cancelled before 1st:Thought Pd Debt',"select_type":'MANUAL',"name": 'Cancelled_before_1st_Thought_Pd_Debt'},
    {"value": 'Cancelled before 1st:No Contact',"select_type":'MANUAL',"name": 'Cancelled_before_1st_No_Contact'},
    {"value": 'Cancelled before 1st:NSF-No Contact',"select_type":'MANUAL',"name": 'Cancelled_before_1st_NSF-No_Contact'},
    {"value": 'Cancelled before 1st:Not Sending Documents',"select_type":'MANUAL',"name": 'Cancelled_before_1st_Not_Sending_Documents'},
    {"value": 'Cancelled after 1st:Lose Job',"select_type":'MANUAL',"name": 'Cancelled_after_1st_Lose_Job'},
    {"value": 'Cancelled after 1st:Bankruptcy',"select_type":'MANUAL',"name": 'Cancelled_after_1st_Bankruptcy'},
    {"value": 'Cancelled after 1st:Self Settlement',"select_type":'MANUAL',"name": 'Cancelled_after_1st_Self_Settlement'},
    {"value": 'Cancelled after 1st:Find another company',"select_type":'MANUAL',"name": 'Cancelled_after_1st_FindAnotherCompany'},
    {"value": 'Cancelled after 1st:Can not Afford',"select_type":'MANUAL',"name": 'Cancelled_after_1st_Can_Not_Afford'},
    {"value": 'Cancelled after 1st:Thought Pd Debt',"select_type":'MANUAL',"name": 'Cancelled_after_1st_Thought_Pd_Debt'},
    {"value": 'Cancelled after 1st:No Contact',"select_type":'MANUAL',"name": 'Cancelled_after_1st_No_Contact'},
    {"value": 'Cancelled after 1st:NSF-No Contact',"select_type":'MANUAL',"name": 'Cancelled_after_1st_NSF-No_Contact'},
    {"value": 'Cancelled after 1st:Not Sending Documents',"select_type":'MANUAL',"name": 'Cancelled_after_1st_Not_Sending_Documents'},
    {"value": 'Transfer',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_Transfer'},
    {"value": 'Transfer is selected',"select_type": 'MANUAL', "name":'Sales_ActiveStaffmembers'},
    {"value": 'Attempted Contact',"select_type": 'AUTO', "name":'Sales_ActiveStatus_AttemptedContact'},
    {"value": 'Appointment Set',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_AppointmentSet'},
    {"value": 'Budget Complete Only',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_BudgetComplete' },
    {"value": 'Resend Contract',"select_type": 'MANUAL', "name":'Sales_Status_ResendContract' },
    {"value": 'Assign to Acct Manager is selected',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_AssignAcctManger_Selected' },
    {"value": 'Sales Issue Resolved',"select_type": 'MANUAL', "name":'Sales_ActiveStatus_SalesIssuesResolved' },
    {"value": 'Service Issue Resolved',"select_type": 'MANUAL', "name":'Service_ActiveStatus_ServiceIssuesResolved' },
    {"value": 'Cancelled',"select_type": 'MANUAL', "name":'Service_ActiveStatus_Cancelled' },
    {"value": 'Cancelled before 1st',"select_type": 'MANUAL', "name":'Service_ActiveStatus_Cancelled_Before' },
    {"value": 'Cancelled after 1st',"select_type": 'MANUAL', "name":'Service_ActiveStatus_Cancelled_After' },
    {"value": 'Dead',"select_type": 'MANUAL', "name":'Sales_DeadStatus_ListofOptions' },
    {"value": 'Dead before 1st',"select_type": 'MANUAL', "name":'Sales_DeadStatus_Before_1st' },
    {"value": 'Closed',"select_type": 'MANUAL', "name":'Sales_ClosedStatus_ListofOptions' },
]


def seed_client_disposition_values():
    for dispo_item in client_dispositions:    
        existing_dispo = ClientDisposition.query.filter_by(name=dispo_item['name']).first()
        if not existing_dispo:
            new_dispo = ClientDisposition(
                public_id=str(uuid.uuid4()), 
                value=dispo_item['value'], 
                select_type=dispo_item['select_type'], 
                name=dispo_item['name'], 
                inserted_on=datetime.datetime.now(tz=utc)
            )
            db.session.add(new_dispo)
    db.session.commit()
